service: lambda-ftp-to-gsheet-transform
# app and org for use with dashboard.serverless.com
app: lambda-ftp-to-gsheet-transform
org: dankez

custom:
  bucket: ${env:S3_BUCKET_NAME}
  alerts:
    stages:
      - dev
      - prod
    topics:
      alarm:
        topic: ${self:service}-${opt:stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${env:ALERTING_EMAIL_ADDRESS}
    alarms:
      - functionErrors
      - functionThrottles

provider:
  name: aws
  runtime: python3.8
  environment:
    USE_PARAMETER_STORE: True
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:GetObject
        - s3:GetObjectAcl
        - s3:ListObjects
        - s3:ListObjectsV2
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::${self:custom.bucket}"
        - "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: "arn:aws:ssm:#{AWS::Region  }:#{AWS::AccountId}:parameter/*"

functions:
  ftp_to_s3_handler:
    handler: handlers.handler_transfer_editrade_files_to_s3
    timeout: 510
    events:
      - schedule: rate(10 minutes)

  # Run a nightly backfill just in case there were any errors
  nightly_backfill:
    handler: handlers.handler_bulk_parse_xml_files
    timeout: 900 # 15 min max timeout
    events:
      - schedule: cron(0 20 * * ? *) # Every night at 9 pm EST

  # Run a nightly backfill just in case there were any errors
  monthly_cleanup:
    handler: handlers.handler_delete_old_files
    timeout: 900 # 15 min max timeout
    events:
      - schedule:
          rate: cron(0 21 * * ? *) # Every night at 10pm EST
          input:
            days_back: 30
            dry_run: false

  send_to_google_sheets:
    handler: handlers.handler_parse_s3_xml_file_to_sheet
    events:
      - s3:
          bucket: "${self:custom.bucket}"
          event: s3:ObjectCreated:*
          rules:
            - prefix: EDITRADEOUT/002113/
            - suffix: .xml

  bulk_send_to_google_sheets:
    handler: handlers.handler_bulk_parse_xml_files
    timeout: 180

plugins:
  - serverless-python-requirements
  - serverless-plugin-aws-alerts
  - serverless-dotenv-plugin
  - serverless-pseudo-parameters
